[build]
  functions = "functions"  # 指定函数目录

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200